/* 
1. NAME 다음에 PET 정보를 추가합니다. PET의 자료형은 VARCHAR(10)입니다.
2. 가장 맨 앞에 GENDER를 추가합니다. GENDER의 자료형은 CHAR(1)이며, NULL일 수 없습니다.
3. MV_NOTI를 NOTICE로 변경합니다. 자료형 또한 VARCHAR(20)으로 변경합니다.
4. HV_CAR 칼럼을 삭제합니다.
5. DWELLERS 필드 정보를 출력합니다.
*/
ALTER TABLE DWELLERS ADD GENDER CHAR(1) NOT NULL FIRST;
ALTER TABLE DWELLERS ADD PET VARCHAR(10) AFTER NAME;

ALTER TABLE DWELLERS CHANGE MV_NOTI NOTICE VARCHAR(20);

ALTER TABLE DWELLERS DROP HV_CAR;
DESC DWELLERS;