ALTER TABLE EMP_ORDER ADD CONSTRAINT FK_ORDER_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES EMP(EMP_ID)
	ON UPDATE SET NULL
	ON DELETE CASCADE;

SELECT * FROM EMP_ORDER;
UPDATE EMP SET EMP_ID = 9876 WHERE EMP_ID = 1001;
SELECT * FROM EMP_ORDER;
DELETE FROM EMP WHERE EMP_ID = 1002;
SELECT * FROM EMP_ORDER;