CREATE TABLE CON5(
ID			INT(10)		NOT NULL	AUTO_INCREMENT	PRIMARY KEY,
NAME		CHAR(15),
GENDER	    CHAR(1)		DEFAULT 'M',
CNT			INT(10)		NOT NULL
);

INSERT INTO CON5(NAME, GENDER, CNT) VALUES ('Lee', 'F', 2);
SELECT * FROM CON5;

INSERT INTO CON5(NAME, CNT) VALUES ('Brian', 3);
SELECT * FROM CON5;

INSERT INTO CON5(NAME, CNT) VALUES ('Park', 4);